services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pencil-postgres
    restart: always
    environment:
      POSTGRES_USER: ritesh
      POSTGRES_PASSWORD: ritesh25
      POSTGRES_DB: pencil
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pencil-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pencil.io
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis:7
    container_name: pencil-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: pencil-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  livekit:
    image: livekit/livekit-server:latest
    container_name: pencil-livekit
    restart: always
    command: ["--config", "/etc/livekit.yaml", "--bind", "0.0.0.0"]
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
  rabbitmq_data:
