name: Production Deployment

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/118266173635/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'pencil-storage-manager@project-9a30612f-91c5-4636-ac1.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Docker Auth
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Http Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/http-backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mypencil/http-backend:latest

      - name: Build and Push WS Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/ws-backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mypencil/ws-backend:latest

      - name: Build and Push AI Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/ai-service/Dockerfile
          platforms: linux/amd64
          push: true
          tags: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mypencil/ai-service:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Cluster via Hub
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 34.131.66.105
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Update Node 1
            ssh -o StrictHostKeyChecking=no 10.190.0.3 "cd ~/mypencil/app && docker system prune -af && docker compose pull && docker compose up -d"
            
            # Update Node 2
            ssh -o StrictHostKeyChecking=no 10.190.0.4 "cd ~/mypencil/app && docker system prune -af && docker compose pull && docker compose up -d"
